### ISSUE TITLE
SQL error when matching vlan attribute with string

### ISSUE THREAD

**Issue by garberg** [SpriteLink/NIPAP#1007]
Trying to match the prefix VLAN attribute to a string leads to an SQL error being shown to the user:
```
$ nipap a l vlan=foo
Searching for prefixes in any VRF...
Command failed: invalid input syntax for integer: "foo"
LINE 97:                         WHERE  inp.vlan = 'foo' 
                                                   ^
```
We should probably implement a "catch-all" try-catch clause which catches all SQL errors and returns a more user-friendly error message.

**Comment by plajjan** [comment]
Not just VLAN.. it's any integer attribute, such as 'indent'.

**Comment by plajjan** [comment]
But your suggested fix will catch the error too late.. for "type" we reasoned differently and put the check in smart_parsing, so before the SQL query is run whereas here you suggest to do it afterwards.

Naturally we can do both, i.e. it might be useful to catch this in case someone feeds us a dictSQL in the search_prefix() RPC (not smart_search_prefix()) but I think the correct fix for normal search (which is smart_search based) is to catch it in the smart parser.

**Comment by plajjan** [comment]
Half of this is done, i.e. we catch exceptions and throw more friendly error messages to the user but the other half is about actually catching the exception before we run the SQL query so that we instead can return an error in the search interpretation.

I'm closing this one as I've opened #1067 to track that last bit.
