### ISSUE TITLE
Local variables support

### ISSUE THREAD

**Issue by ingroxd** [SpriteLink/NIPAP#1177]
Hi, I recently installed NIPAP on Debian Stretch (After failing in making it run on RedHat 7.4).

I am trying some things and in particular i noticed that nipap-cli can read some local variables, like:
- NIPAP_HOST;
- NIPAP_PORT;
- NIPAP_USERNAME;
- NIPAP_PASSWORD.

If no `.nipaprc` file is created, using the autocompletion on command `nipap` suggests to export those variables; after that, autocompletion starts to work as intended.

The problem is that when the command is launched, it goes for `.nipaprc` ignoring those variables.
Is it possible to integrate local variables support?
It would be very useful for us storing the password in a local temp var instead of writing it as clear text in the rc file!

Just for info, I used the official github repo for Debian.

**Comment by plajjan** [comment]
Hmm, yes, we do honour those environment options (https://github.com/SpriteLink/NIPAP/blob/master/nipap-cli/nipap_cli/nipap_cli.py#L55) but at the same time we require a .nipaprc file to exist (https://github.com/SpriteLink/NIPAP/blob/master/nipap-cli/nipap#L59). I suppose we could start by checking if the env vars are set and if they are, we don't actually require .nipaprc to exist.

However, to get around the problem, you should be fine with creating an empty .nipaprc file.

**Comment by ingroxd** [comment]
I was thinking about mixing them up...
Something like, some info in the rc file and some info in environment variables.
Also, if no username is provided, nipap could grab the logged user [:

Those are just ideas, I don't know if they could be useful to others, but imho it would be safer not store the password as clear text!

I would like to read what do you think about it [:

**Comment by plajjan** [comment]
Sure, storing passwords in cleartext is suboptimal although it's nothing new, for example, look at .netrc which is used and supported by many applications.

We do try to help the user by checking the ownership and permissions on the file as to prevent having a world readable file.

Other systems that keep credentials on file use a token. We could move in that direction but it's non-trivial to implement.

You can mix and match between config file and env var AFAIR. The problem you initially ran into and reported in this issue is because you have no .nipaprc file at all. If you want to mix then you would have one and thus it shouldn't be a problem. I think if no password is provided in the config file, you will be interactively prompted for one.

Using $USER as a default of last resort would also be an option, yes. I'm happy to accept PR for this :)
