### ISSUE TITLE
Some prefixes are grey

### ISSUE THREAD

**Issue by dosomder** [SpriteLink/NIPAP#466]
I would like to bring this issue back. I already described it here https://github.com/SpriteLink/NIPAP/issues/405#issuecomment-24314025

I was advised by plajjan that this issue should be a problem with the system, not with the database.
So I set up a fresh new ubuntu, installed nipap according to the 'Getting started' guide and imported my database using my import script (https://github.com/dosomder/NIPAP/commit/2b109c4cd27ce5218d006a99edab7978798e6d6c).
```
root@ubuntu:/tmp# nipapd --version
nipapd version: 0.23.2
```

However, the issue is still present:
![problem](https://f.cloud.github.com/assets/3040570/2097550/80195244-8f1a-11e3-8f36-67b0ae0d7861.png)

I hope we can solve this. Thanks

**Comment by spaprzycki** [comment]
Hi,
I am just starting using NIPAP, importing medium size IPPlan to it. Just saw being hit by the same bug. Initially I spent some time trying to figure out what I have done differently for some of those prefixes, but then found this which perfectly explains it.

Do you have any idea what is causing this?

It looks like 'row_collateral' class is added, which makes prefixes grey, but cannot find it within a code anywhere else then when displaying search result..

I am running 0.27.4 - newest I can get from your deb repository.

Regards,
Sergiusz

**Comment by dosomder** [comment]
Hello,

I have already posted the problem / fix a few comments above :) I don't think this problem is high priority so I guess you're better off fixing it yourself.

**Comment by DanAnkers** [comment]
I've done a bit of poking around on this.

The issue appears to be that the greyed out prefixes are being returned from /xhr/smart_search_prefix with the property "match = false".  The ones which are displayed normally have "match = true".

"match = false" is being set because the query passed to /xhr/smart_search_prefix (specified in collapseClick() in nipap.js) has "max_result" set to 1000 - so prefixes after the 1000th returned by this search get greyed out.  I've tested this by increasing max_result to a large value, which successfully hides the problem.

What I've not got my head around yet is why /xhr/smart_search_prefix is returning more results than max_result says it should.
