### ISSUE TITLE
Installation error message

### ISSUE THREAD

**Issue by crgauth** [SpriteLink/NIPAP#716]
I'm probably missing something simple but getting the following error when trying to run setup script:
dli@DLI~/NIPAP/nipap $ python setup.py install
rst2man failed to run: [Errno 2] No such file or directory

I am running this on Linux Mint 17.1 (unbuntu derivative)﻿

**Comment by plajjan** [comment]
The official and supported way of installing NIPAP is via debian packages which is why some other procedures are slightly less tested. This wiki page https://github.com/SpriteLink/NIPAP/wiki/Building-Debian-packages outlines the packages you need to build the Debian and in this particular case you run into the same lack of binaries, ie you need rst2man from the python-docutils debian package, which I suppose would be named the same on Mint.

This is just to generate a man page from a .rst file, so it's not crucial for nipap itself...

**Comment by crgauth** [comment]
So does this mean that nipap will not work on an Unbuntu based distro?
BTW, I did install rst2man.
Error message I am getting looks like some file is not located in a directory that install script is expecting.

**Comment by plajjan** [comment]
I have never worked with Mint so I can't really answer for it with certainty, but if it is Ubuntu based, I suggest you try to use the official Debian/Ubuntu packages instead of trying to install it via Python distutils.

See http://spritelink.github.io/NIPAP/docs/install-debian.html

**Comment by plajjan** [comment]
I'm closing this as I don't see any problem with NIPAP itself. I did fiddle around a bit with setup.py, see #772. Not sure if it's a good idea or not but it would "fix" the situation @crgauth ran into here.
