### ISSUE TITLE
API doc incorrectly says edit_prefix takes "spec" argument

### ISSUE THREAD

**Issue by toreanderson** [SpriteLink/NIPAP#750]
From http://nipap-plajjan.readthedocs.org/en/latest/nipap.html#nipap.backend.Nipap.edit_prefix:
```
spec [prefix_spec]
    Specifies the prefix to edit.
```
That doesn't work, however. This should probably read `prefix [prefix_spec]` instead (which does work).

For what it's worth I see that the `spec` attribute is mentioned for other API calls too, so maybe the same mistake is made elsewhere.

**Comment by plajjan** [comment]
Ah yes. Technically, the docs are correct. You are looking at the docs for the backend module and its argument is called spec. However, we have the XML-RPC wrapper around the backend to expose its methods over the XML-RPC API and that method  takes an argument called 'prefix'. I believe if you look at that methods docs you will find that the argument is called prefix. 

Since we want to avoid duplication we have tried to put as much documentation in the backend module so that readers should not have to look around in a lot of places to understand the design. This is an example where the reader would have to look around in multiple places and there is no reason for it. I suggest we simply rename the argument in one of the functions so that they are called the same.

**Comment by toreanderson** [comment]
Ah, quite right you are! I hadn't realised those were two distinct parts of the documentation, sorry about the noise. If you want to close this issue, do feel free.

FWIW the way I found out that `prefix` was used instead of `spec` was by resorting to tcpdumping the XML-RPC traffic between the web interface and the backend. :-)

**Comment by plajjan** [comment]
No, I won't close this. I think it's excellent proof that the current documentation is not clear. In addition, you are referencing my private build of the docs instead of the official docs, which made me notice that the API docs is actually missing in the official docs (as per #754).

Not quite sure how we should solve it though.
* Better cross referencing between the "NIPAP API" (which is really just the internal backend module) and the XML-RPC API (which most people will expect)
* Have complete docs for the XML-RPC API. The reason I don't like this is because if we do add a second wrapper around the backend module, like a JSON-RPC API, we would have to completely duplicate all the documentation on how a particular module behaves.
* Something else?

**Comment by garberg** [comment]
I have done some work on pynipap similar to this while looking into #712. It includes your first point, cross references from pynipap functions to their respective backend function. It works fine building the docs locally using sphinx, but when building on readthedocs the references are simply not turned into links from some reason.

Oh, now I see that the NIPAP API part is missing entirely as described in #754, that might be related :laughing: 

Another point to add might be to unify naming of the function arguments in the XML-RPC functions and backend functions, ie. call the prefix specification "prefix" instead of "spec" in the backend function header as the XML-RPC function dict key is called.

**Comment by plajjan** [comment]
@garberg I fixed #754 so whatever tests you want to do you should be able to do now!

**Comment by plajjan** [comment]
I've opened #771 which more closely describes one of the issues pointed out in this issue, ie the mismatch of argument names between backend and xml-rpc. The other part of adding references in the documentation is handled by #758 so I'm closing this issue.
