### ISSUE TITLE
Update doc on Apache configuration

### ISSUE THREAD

**Issue by plajjan** [SpriteLink/NIPAP#796]
http://spritelink.github.io/NIPAP/docs/config-www.html only mentions adding a wsgiscriptalias line.. but per default apache will not allow those requests. On Debian jessie, with Apache 2.4.10 I had to add this:
```
        <Directory /etc/nipap/>
                Require all granted
        </Directory>

        WSGIScriptAlias / /etc/nipap/nipap-www.wsgi
```

Not the Directory clause which looks different in Apache 2.4 compared to Apache 2.2

**Comment by plajjan** [comment]
I think we should have examples for Apache 2.4 and 2.2...

Are there any downsides / risk with allowing access to /etc/nipap, given that we have sensitive stuff there, like nipap.conf that contains the db credentials? Ie, should the wsgi file be moved elsewhere?

**Comment by SoundGoof** [comment]
other pkg uses a www directory inside, eg /etc/nipap/www for stuff like this

**Comment by plajjan** [comment]
We could certainly do that!

**Comment by crlsgms** [comment]
I just installed the nipap through the packages avaiable on debian, but I agree there are some infos missing if you want for example to use multiple aplications on this server, a simple vhost example with suitable requisites to apache run nipap would be awesome. 

Ill appy some options here and if I suceed ill update here

**Comment by crlsgms** [comment]
Well, trying to setup here I had some help on irc by kll, and some issues appeared since Im using the latest debian release. The first step was to setup a working virtual host for the nipap service, since ill use this server for aditional vhosts, its prefereable to have a separated setup for nipap. 

My apache config under /sites-avaiable/nipap.my.domain.com.conf was:
```
<VirtualHost *:80>
      ServerName nipap.mydomain.com
      DocumentRoot /var/cache/nipap-www/
      ServerAdmin cgomes@franca.unesp.br

<Directory "/var/cache/nipap-www">
  AddDefaultCharset utf8
  AllowOverride None
      Order allow,deny
      # Allow from all
      # Allow from 68.68.64.55 (I wished to lock up access from some ips, didnt worked yet)
</Directory>

<Ifmodule mod_wsgi.c>
        <Directory /etc/nipap>
        Options None
        Require all granted
        </Directory>
        WSGIScriptAlias / /etc/nipap/nipap-www.wsgi
</IfModule>

   ErrorLog ${APACHE_LOG_DIR}/nip.error.log
   CustomLog ${APACHE_LOG_DIR}/nip.access.log combined

</VirtualHost>

```
and after adding those lines, yet the application gave some errors on the page "server error 500", and on the server logs I had this 111:
>[Mon Jun 29 16:11:43.529175 2015] [wsgi:error] [pid 1398:tid 140506214389504] [client 10.10.10.55:62450] Error - <class 'socket.error'>: [Errno 111]

the solution was to change my sources.list.d/nipap repo from stable to testing, so I got version .28 where this was fixed. 

Now Ill try to populate the addresses, but if someone was trying to work with debian / vhosts maybe this would help. 

Actually I need some help regarding the security part, I wish to restrick ips to access the interface, since other vhosts would be also avaiable on this machine. Maybe isnt the right line of thought, but would work nicely on our intranet :D

**Comment by yostie** [comment]
I am having some issues with getting nipap working as well on newer Ubuntu distro.  I follow some of the suggestions above for apache 2.4, but I'm still having no luck.  If I look at the apache logs, i see the following:

[Thu Dec 17 13:19:09.388826 2015] [autoindex:error] [pid 717:tid 140350802577152] [client 172.30.251.16:55095] AH01276: Cannot serve directory /var/cache/nipap-www/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive

If I go and look at /var/cache/nipap-www, there are no files in there.  I don't believe I skipped any steps and I definitely did an install of the nipap-www package.

**Comment by plajjan** [comment]
@yostie I've completely missed your feedback here. If you are still pursuing this please open a separate issue :)

**Comment by yostie** [comment]
Nope im all set.  Thanks for the followup.

Sent from Outlook Mobile




On Sat, Jan 30, 2016 at 3:17 AM -0800, "Kristian Larsson" <notifications@github.com> wrote:












@yostie I've completely missed your feedback here. If you are still pursuing this please open a separate issue :)
