### ISSUE TITLE
update display_prefix

### ISSUE THREAD

**Issue by plopezpivotal** [SpriteLink/NIPAP#799]
Note sure if this is intended or not. but when adding a Host in a prefix the host display_prefix is the same and the network prefix. example 10.10.10.0/24 (ASSIGNMENT) host 10.10.10.1/32 has a 10.10.10.1/24 display_prefix. 

I understand that this is related to the postgres data type of inet which is used. From a UI standpoint I think some might be confused by this as the UI uses the display_prefix. I attempted to update the Object via pynipap but it looks like this is not being mapped. I was able to change the data by modifying the data direct in the database (as a test) and the display_prefix does then reflect the /32 for the host.

Is this implementation by design?

**Comment by plajjan** [comment]
That is per design but doesn't have much to do with Postgres, we would likely have a similar design if we used a different database. You are not supposed to try to edit display_prefix - it is automatically filled in.

We want a unique prefix column to guarantee uniqueness, which is what the "prefix" column is there for. At the same time we want prefixes to be displayed with their natural net mask, i.e. the net mask of the network they are in, thus display_prefix. The reason the "prefix" cannot contain the natural net mask of a prefix is because then the uniqueness would prevent us from registering both a network and a host for the same address. For a /31 network, where the first host address and the network address is the same, we still need to be able to differentiate between them, so the network is registered with a /31 net mask while the host is registered with a /32 mask.

Does this make sense?

**Comment by plopezpivotal** [comment]
Yes this does make sense. So is that not why there are prefix Type's as well? in the case of the /31 would that not be of type assignment and the actual host of type Host? Or am I confused here? I would assume using they Type field would address this use case.

**Comment by plajjan** [comment]
Yeah a /31 link network would be of type "assignment" and the two end hosts in that network would be of type "host".

The whole prefix type is an artificial construct and I've been working a bit on simplifying it... Since you can have /32 as part of a network as well as configured (for something like a loopback) we still have the need to differentiate between them using type, but I think it can be made easier to work with.

**Comment by plajjan** [comment]
I am closing this. Please reopen or create new issue if you have further issues :)
