### ISSUE TITLE
pynipap.NipapError: <type 'exceptions.UnboundLocalError'>:local variable 'q' referenced before assignment

### ISSUE THREAD

**Issue by LordAro** [SpriteLink/NIPAP#843]
I believe I've found a bug - I'm not entirely sure how I'm triggering it, and what I'm doing is likely wrong, but I don't think it should be returning this response

I've tracked down the erroring code to https://github.com/SpriteLink/NIPAP/blob/master/nipap/nipap/backend.py#L991

**Comment by LordAro** [comment]
Done some more digging and the line
`updated = function(auth, q, { 'max_result': 10000 })['result']`
is definitely at fault if `len(qps) == 0`

Not sure what the correct solution would be though

**Comment by plajjan** [comment]
Definitely seems to be a bug in there. If you update something but it doesn't actually match anything to update you will take a code path through that function where q is not set.

**Comment by plajjan** [comment]
@LordAro if you have the possibility, please do try to test the code in the PR I just submitted to verify if it works :)

**Comment by LordAro** [comment]
Appears to work! I get a different error - `pynipap.NipapError: Prefix edit returned 0 entries, should be 1.` but that's not entirely unexpected

For reference, I'm "trying" to set the id of the prefix before saving it - I think this is the wrong thing to do, no?

**Comment by plajjan** [comment]
@LordAro indeed, the id is set by the backend when you add a new one.

pynipap determines if a prefix is new or an existing one based on if it has the id set. Since you are setting it, pynipap will assume that the prefix already exists in the db, so when you run save() on it, it will run edit_prefix and not add_prefix towards the backend. The prefix doesn't actually exist in the backend so edit_prefix will fail.

**Comment by LordAro** [comment]
Figured as such :)

I found a different (and no doubt better) way, regardless
