### ISSUE TITLE
When listing prefixes in cli, missing values are displayed as None

### ISSUE THREAD

**Issue by emjemj** [SpriteLink/NIPAP#861]
When listing prefixes with nipap address list, values not filled in are displayed as None, maybe there should not be anything written out. This is a purely cosmetic issue, but I think it looks wierd.

**Comment by plajjan** [comment]
This has been discussed before, see #48. I'm sure there are other related issues as well.

Not printing something, i.e. '', would make output much more difficult to parse using AWK or whatever else you might do from the command line since you would essentially have variable number of columns. You can't rely on the width of the columns staying the same either as they are variable based on the width of your data.

If this is just about changing 'None' to something else, what would you then suggest?

**Comment by plajjan** [comment]
I'm actually going to close this one. If you feel you have a suggestion for something better than 'None', feel free to reopen.
