### ISSUE TITLE
No way to change user password

### ISSUE THREAD

**Issue by bootc** [SpriteLink/NIPAP#871]
There doesn't appear to be a means to change a user's password. Neither the `nipap-passwd` tool nor the web interface appear to offer any means to change one's password. If this functionality does exist, the documentation appears to be inadequate to point one towards it.

**Comment by plajjan** [comment]
You are right, it is not possible. As can be seen here https://github.com/SpriteLink/NIPAP/blob/master/nipap/nipap-passwd#L21 the only options are to add or delete a user. There is no choice to update an existing user and we should obviously have that, just haven't gotten around to it ;)

**Comment by plajjan** [comment]
So one of the tricky things around this is that we can't really keep the current argument parsing. When adding a user we default the 'trusted' and 'readonly' values to False and they are set to True with --trusted or --readonly. But when modifying an existing user I think we should try not to touch the whole row and only update the values that the administrator actually wants, for example, to update the name, we would have:
```
nipap-passwd modify --username foo --name "My test user"
```
And I would expect this to only modify the name of the user. Whatever the value of trusted or readonly is, it should remain as is. The problem is that you can't specify "not trusted" with command arguments, it is only assumed by the lack of the --trusted flag. See?

Either we put an argument to --trusted, so `--trusted true` or we introduce a '--not-trusted' and similarly for the readonly flag.

**Comment by plajjan** [comment]
Another reason we never got around to this is that I wanted to move into using sqlalchemy. I found the branch in my local clone but I think it's rather far from complete so I just did it the good ol' way now.

**Comment by plajjan** [comment]
I'll let @garberg review the PR before merging. Hopefully he'll be able to do that within the not too distant future. Also, we need to wrap up 0.29 which is way overdue.
