### ISSUE TITLE
Various pynipap documentation updates

### ISSUE THREAD

**Issue by crosson** [SpriteLink/NIPAP#992]
Hi Team,

Tada. This is my first ever pull request. In retrospect I realize I kind of unloaded on the pynipap.py commented section on the top. My team and I have been eagerly playing with the tool but running into a few setup and usability hiccups that I believe could have been avoided with tad bit more documentation.

My updates are in [PR 991](https://github.com/SpriteLink/NIPAP/pull/991)

If I've been too forward and done a bit too much let me know!  This is a learning experience for me so I take no offense to the scrutiny. 

Also I noticed that the sphinx documentation isn't updated as well. I'd love to regenerate this, however that is done, and get other changes found in the code reflected on the documentation pages.

**Comment by crosson** [comment]
#991

**Comment by plajjan** [comment]
I've merged #991 to master. There might have been one or two things that could have been improved in that PR but seeing how the PR brings an improvement I choose to simple merge it rather than dwell over potential nitpicks.

Documentation updates, feature enhancements and bug fixes are very welcome! :)

What part of the sphinx documentation is outdated? The documentation is automatically generated from git and published at http://nipap.readthedocs.io/ - in the menu down to the left you can pick which git tag you want to view (like master or 0.28.4).

**Comment by crosson** [comment]
I see my issue is not viewing the latest for the documentation piece. Thank you @plajjan. 

Any advise you can lend on how to approach future PR's I am all ears. If I get an opportunity in the future I'd love to contribute more. Even if the contribution is small in size.
